# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5cfe85873ea40e0789a002f011ada9dd9df7999d89072d4c6a3599697c5bc04db47cc4cb068ac38abc31668a2df053a86d0518e1cfaeb0cb1f093e8b8bdeb905

test:
  secret_key_base: 51772e67fa473241c757d4275d03b7187348be52654f446502486971726e2a608b56659502c33594e956cb0b094a491cd453fd0857362fe7cb5b2e9cd058fb82

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
