# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52b104cc6cb4430e3d4f23f2c9b3d50ef86935bb91035a6ea8cf7931e8198d1c824edd2f63e008bc113fadb3bc746685f892190ecd78e690ab336d90a2e5584e

test:
  secret_key_base: 93f14930edfcdbec2bce79ae943e57d963edff069933ee93fa4b2f206fa5350c81bf5bb758ec12ccfcccf673484f4505f4782a216e5ec91757f0afa0b60ab171

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
